# Generated by Django 5.2.3 on 2025-06-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0002_agent_remove_chatmessage_response_agentresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentresponse',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentresponse',
            name='chat_message',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='agent_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice_agent.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_text',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='AgentResponse',
        ),
    ]
