# Generated by Django 5.2.3 on 2025-06-24 09:47

import django.utils.timezone
import voice_agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0003_remove_agentresponse_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=voice_agent.models.document_upload_path),
        ),
    ]
