# Generated by Django 5.2.3 on 2025-06-26 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='interrupted_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_interruption',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_discussion_active', models.BooleanField(default=False)),
                ('current_agent_id', models.IntegerField(blank=True, null=True)),
                ('discussion_turn', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice_agent.document')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceInterruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_message_id', models.IntegerField()),
                ('interruption_text', models.TextField()),
                ('interruption_confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice_agent.conversationsession')),
            ],
        ),
    ]
