# Generated by Django 5.2.3 on 2025-06-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0006_chatmessage_interrupted_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceinterruption',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='interrupted_message_id',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_interruption',
        ),
        migrations.DeleteModel(
            name='ConversationSession',
        ),
        migrations.DeleteModel(
            name='VoiceInterruption',
        ),
    ]
