# Generated by Django 5.2.3 on 2025-06-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0007_remove_voiceinterruption_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='debug_transcript_history',
            field=models.TextField(blank=True, help_text='Debug: Full transcript history at this point', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='agent_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
