# Generated by Django 5.2.3 on 2025-06-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_agent', '0008_rename_timestamp_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='debug_transcript_history',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='agent_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_text',
            field=models.TextField(blank=True),
        ),
    ]
